### ISSUE TITLE
[Bug]: AttributeError when fetching /api/round

### ISSUE THREAD

**Issue by burnedinthesky** [fan9704/Drawing-Competition-Backend#39]
### 發生了甚麼? What happened?

在 GET /api/round 時會 500

### OS Version

Linux

### 提供相關的 log 輸出 Relevant log output

```shell
Traceback (most recent call last):
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/fields.py", line 439, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/fields.py", line 106, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtin_function_or_method' object has no attribute 'start_time'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django_extensions/management/technical_response.py", line 40, in null_technical_500_response
    raise exc_value.with_traceback(tb)
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Projects/Drawing-Competition-Backend/api/views/round.py", line 37, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.cache/pypoetry/virtualenvs/equipment-backend-P9fZ2XNv-py3.12/lib/python3.12/site-packages/rest_framework/fields.py", line 472, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `start_time` on serializer `RoundChallengeSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `builtin_function_or_method` instance.
Original exception text was: 'builtin_function_or_method' object has no attribute 'start_time'.
```

### 行為準則 Code of Conduct

- [X] 我同意本專案的行為準則 I agree to follow this project's Code of Conduct

**Comment by fan9704** [comment]
已修復
